'use strict';
/* =====================================================================
   MacroFit · base de datos local
   Valores nutricionales por 100 g (referencia BEDCA / USDA, redondeados).
   Carnes y pescados en crudo; arroz, pasta y legumbres cocidos (se indica).
   ===================================================================== */

const CATS = {
  prot: { l: 'Proteínas', e: '🍗' },
  lact: { l: 'Lácteos y bebidas', e: '🥛' },
  cer: { l: 'Cereales y tubérculos', e: '🍚' },
  leg: { l: 'Legumbres', e: '🫘' },
  ver: { l: 'Verduras', e: '🥦' },
  fru: { l: 'Frutas', e: '🍎' },
  gra: { l: 'Grasas y frutos secos', e: '🥜' },
  otr: { l: 'Otros', e: '🍯' }
};

// [nombre, categoría, kcal, prot, hidr, grasa, unidad, gramos/unidad, emoji?]
const FOOD_ROWS = [
  // ---- Proteínas ----
  ['Pechuga de pollo (cruda)', 'prot', 110, 23, 0, 1.5, 'filete', 150, '🍗'],
  ['Muslo de pollo sin piel (crudo)', 'prot', 121, 20, 0, 4.5, 'muslo', 120, '🍗'],
  ['Pechuga de pavo (cruda)', 'prot', 105, 24, 0, 1, 'filete', 150, '🦃'],
  ['Ternera magra / solomillo (crudo)', 'prot', 143, 22, 0, 6, 'filete', 150, '🥩'],
  ['Ternera picada magra 5% (cruda)', 'prot', 137, 21, 0, 5.5, 'hamburguesa', 120, '🥩'],
  ['Lomo de cerdo (crudo)', 'prot', 143, 21, 0, 6, 'filete', 150, '🥩'],
  ['Huevo entero', 'prot', 143, 12.6, 0.7, 9.5, 'huevo', 55, '🥚'],
  ['Clara de huevo', 'prot', 52, 10.9, 0.7, 0.2, 'clara', 33, '🥚'],
  ['Salmón (crudo)', 'prot', 208, 20, 0, 13, 'lomo', 150, '🐟'],
  ['Merluza (cruda)', 'prot', 71, 16, 0, 0.8, 'filete', 150, '🐟'],
  ['Bacalao fresco (crudo)', 'prot', 82, 18, 0, 0.7, 'lomo', 150, '🐟'],
  ['Dorada (cruda)', 'prot', 121, 20, 0, 4.2, 'ración', 150, '🐟'],
  ['Lubina (cruda)', 'prot', 97, 18, 0, 2.5, 'ración', 150, '🐟'],
  ['Atún al natural (lata)', 'prot', 116, 26, 0, 1, 'lata', 52, '🐟'],
  ['Atún en aceite (escurrido)', 'prot', 198, 29, 0, 8.2, 'lata', 52, '🐟'],
  ['Sardinas en lata', 'prot', 208, 25, 0, 11.5, 'lata', 85, '🐟'],
  ['Caballa (cruda)', 'prot', 205, 19, 0, 14, 'filete', 120, '🐟'],
  ['Gambas (crudas)', 'prot', 85, 18, 0.2, 1.1, 'ración', 150, '🦐'],
  ['Mejillones (crudos)', 'prot', 86, 12, 3.7, 2.2, 'ración', 150, '🦪'],
  ['Pulpo (cocido)', 'prot', 164, 30, 4.4, 2.1, 'ración', 150, '🐙'],
  ['Calamar (crudo)', 'prot', 92, 15.6, 3.1, 1.4, 'ración', 150, '🦑'],
  ['Salmón ahumado', 'prot', 172, 25, 0, 8, 'ración', 50, '🐟'],
  ['Jamón cocido extra', 'prot', 110, 18, 1.5, 3.5, 'loncha', 20, '🥓'],
  ['Fiambre de pavo', 'prot', 95, 17, 1.5, 2, 'loncha', 20, '🥓'],
  ['Jamón serrano', 'prot', 241, 31, 0, 13, 'loncha', 15, '🥓'],
  ['Tofu firme', 'prot', 120, 13, 2, 7, 'ración', 150, '🧈'],
  ['Tempeh', 'prot', 192, 20, 7.6, 11, 'ración', 100, '🫘'],
  ['Seitán', 'prot', 130, 25, 5, 1.5, 'ración', 100, '🌾'],
  ['Proteína whey (polvo)', 'prot', 380, 80, 6, 5, 'scoop', 30, '🥤'],
  ['Proteína vegetal (polvo)', 'prot', 370, 75, 8, 6, 'scoop', 30, '🥤'],

  // ---- Lácteos y bebidas ----
  ['Leche semidesnatada', 'lact', 46, 3.4, 4.8, 1.6, 'vaso', 200, '🥛'],
  ['Leche desnatada', 'lact', 35, 3.5, 5, 0.1, 'vaso', 200, '🥛'],
  ['Bebida de soja sin azúcar', 'lact', 33, 3.3, 0.8, 1.8, 'vaso', 200, '🥛'],
  ['Bebida de avena', 'lact', 45, 1, 7.5, 1.5, 'vaso', 200, '🥛'],
  ['Bebida de almendras sin azúcar', 'lact', 15, 0.5, 0.3, 1.1, 'vaso', 200, '🥛'],
  ['Yogur natural', 'lact', 61, 3.5, 4.7, 3.3, 'yogur', 125, '🥣'],
  ['Yogur griego natural', 'lact', 97, 9, 4, 5, 'yogur', 125, '🥣'],
  ['Yogur griego 0%', 'lact', 54, 10, 3.5, 0.2, 'yogur', 125, '🥣'],
  ['Skyr natural', 'lact', 63, 11, 4, 0.2, 'tarrina', 150, '🥣'],
  ['Queso fresco batido 0%', 'lact', 46, 8, 4, 0.2, 'tarrina', 125, '🥣'],
  ['Queso cottage', 'lact', 98, 11, 3.4, 4.3, 'tarrina', 180, '🧀'],
  ['Queso fresco (Burgos)', 'lact', 174, 13, 3.5, 12, 'ración', 50, '🧀'],
  ['Mozzarella light', 'lact', 165, 18, 1, 10, 'bola', 125, '🧀'],
  ['Queso curado', 'lact', 402, 25, 1.3, 33, 'loncha', 20, '🧀'],
  ['Kéfir natural', 'lact', 55, 3.5, 4.5, 3, 'vaso', 200, '🥛'],
  ['Zumo de naranja natural', 'lact', 45, 0.7, 10, 0.2, 'vaso', 200, '🍊'],

  // ---- Cereales y tubérculos ----
  ['Arroz blanco (cocido)', 'cer', 130, 2.7, 28, 0.3, 'ración', 150, '🍚'],
  ['Arroz integral (cocido)', 'cer', 123, 2.7, 25.6, 1, 'ración', 150, '🍚'],
  ['Pasta (cocida)', 'cer', 158, 5.8, 31, 0.9, 'plato', 200, '🍝'],
  ['Pasta integral (cocida)', 'cer', 150, 6, 30, 1.2, 'plato', 200, '🍝'],
  ['Quinoa (cocida)', 'cer', 120, 4.4, 21, 1.9, 'ración', 150, '🌾'],
  ['Cuscús (cocido)', 'cer', 112, 3.8, 23, 0.2, 'ración', 150, '🌾'],
  ['Avena en copos (cruda)', 'cer', 372, 13.5, 60, 7, 'ración', 40, '🌾'],
  ['Muesli sin azúcar', 'cer', 360, 10, 62, 6, 'ración', 40, '🥣'],
  ['Pan integral', 'cer', 247, 9, 41, 3.4, 'rebanada', 30, '🍞'],
  ['Pan blanco', 'cer', 265, 9, 52, 1, 'rebanada', 30, '🍞'],
  ['Pan de centeno', 'cer', 259, 8.5, 48, 3.3, 'rebanada', 30, '🍞'],
  ['Tortilla de trigo (wrap)', 'cer', 300, 8, 50, 7, 'wrap', 60, '🌯'],
  ['Tortita de arroz', 'cer', 387, 8, 82, 3, 'tortita', 9, '🍘'],
  ['Patata (cocida)', 'cer', 86, 1.9, 20, 0.1, 'patata mediana', 150, '🥔'],
  ['Boniato (cocido)', 'cer', 90, 2, 21, 0.1, 'boniato', 150, '🍠'],
  ['Maíz dulce (lata)', 'cer', 86, 3, 19, 1.4, 'lata', 140, '🌽'],
  ['Palomitas (sin mantequilla)', 'cer', 387, 13, 78, 4.5, 'bol', 20, '🍿'],

  // ---- Legumbres ----
  ['Lentejas (cocidas)', 'leg', 116, 9, 20, 0.4, 'plato', 200, '🫘'],
  ['Garbanzos (cocidos)', 'leg', 164, 8.9, 27, 2.6, 'ración', 150, '🫘'],
  ['Alubias (cocidas)', 'leg', 127, 8.7, 23, 0.5, 'ración', 150, '🫘'],
  ['Guisantes (cocidos)', 'leg', 81, 5, 14, 0.4, 'ración', 100, '🫛'],
  ['Edamame', 'leg', 121, 12, 9, 5, 'ración', 100, '🫛'],
  ['Hummus', 'leg', 177, 8, 14, 10, 'cucharada', 25, '🫘'],

  // ---- Verduras ----
  ['Brócoli', 'ver', 34, 2.8, 7, 0.4, 'ración', 150, '🥦'],
  ['Espinacas', 'ver', 23, 2.9, 3.6, 0.4, 'ración', 100, '🥬'],
  ['Lechuga', 'ver', 15, 1.4, 2.9, 0.2, 'ración', 80, '🥬'],
  ['Rúcula', 'ver', 25, 2.6, 3.7, 0.7, 'puñado', 30, '🥬'],
  ['Tomate', 'ver', 18, 0.9, 3.9, 0.2, 'tomate', 120, '🍅'],
  ['Tomate triturado', 'ver', 24, 1.3, 4, 0.2, 'ración', 100, '🍅'],
  ['Pepino', 'ver', 15, 0.7, 3.6, 0.1, 'pepino', 200, '🥒'],
  ['Zanahoria', 'ver', 41, 0.9, 10, 0.2, 'zanahoria', 80, '🥕'],
  ['Calabacín', 'ver', 17, 1.2, 3.1, 0.3, 'ración', 150, '🥒'],
  ['Pimiento rojo', 'ver', 31, 1, 6, 0.3, 'pimiento', 150, '🫑'],
  ['Cebolla', 'ver', 40, 1.1, 9, 0.1, 'cebolla', 110, '🧅'],
  ['Champiñones', 'ver', 22, 3.1, 3.3, 0.3, 'ración', 100, '🍄‍🟫'],
  ['Coliflor', 'ver', 25, 1.9, 5, 0.3, 'ración', 150, '🥦'],
  ['Judías verdes', 'ver', 31, 1.8, 7, 0.2, 'ración', 150, '🫛'],
  ['Berenjena', 'ver', 25, 1, 6, 0.2, 'ración', 150, '🍆'],
  ['Espárragos', 'ver', 20, 2.2, 3.9, 0.1, 'ración', 100, '🌿'],
  ['Calabaza', 'ver', 26, 1, 6.5, 0.1, 'ración', 150, '🎃'],
  ['Remolacha (cocida)', 'ver', 44, 1.7, 10, 0.2, 'ración', 100, '🟣'],
  ['Aguacate', 'ver', 160, 2, 8.5, 14.7, 'medio aguacate', 100, '🥑'],
  ['Kale / col rizada', 'ver', 49, 4.3, 9, 0.9, 'ración', 80, '🥬'],
  ['Ajo', 'ver', 149, 6.4, 33, 0.5, 'diente', 4, '🧄'],
  ['Aceitunas', 'ver', 145, 1, 4, 15, 'puñado', 30, '🫒'],

  // ---- Frutas ----
  ['Plátano', 'fru', 89, 1.1, 23, 0.3, 'plátano', 120, '🍌'],
  ['Manzana', 'fru', 52, 0.3, 14, 0.2, 'manzana', 180, '🍎'],
  ['Naranja', 'fru', 47, 0.9, 12, 0.1, 'naranja', 180, '🍊'],
  ['Mandarina', 'fru', 53, 0.8, 13, 0.3, 'mandarina', 80, '🍊'],
  ['Pera', 'fru', 57, 0.4, 15, 0.1, 'pera', 170, '🍐'],
  ['Fresas', 'fru', 32, 0.7, 7.7, 0.3, 'ración', 150, '🍓'],
  ['Arándanos', 'fru', 57, 0.7, 14, 0.3, 'puñado', 80, '🫐'],
  ['Frambuesas', 'fru', 52, 1.2, 12, 0.7, 'puñado', 80, '🍓'],
  ['Frutos rojos (mezcla)', 'fru', 45, 0.8, 10, 0.4, 'ración', 100, '🫐'],
  ['Kiwi', 'fru', 61, 1.1, 15, 0.5, 'kiwi', 75, '🥝'],
  ['Piña', 'fru', 50, 0.5, 13, 0.1, 'rodaja', 100, '🍍'],
  ['Sandía', 'fru', 30, 0.6, 7.6, 0.2, 'ración', 250, '🍉'],
  ['Melón', 'fru', 34, 0.8, 8, 0.2, 'ración', 200, '🍈'],
  ['Uvas', 'fru', 69, 0.7, 18, 0.2, 'puñado', 100, '🍇'],
  ['Mango', 'fru', 60, 0.8, 15, 0.4, 'ración', 150, '🥭'],
  ['Melocotón', 'fru', 39, 0.9, 10, 0.3, 'melocotón', 150, '🍑'],
  ['Granada', 'fru', 83, 1.7, 19, 1.2, 'ración', 100, '🍎'],
  ['Cerezas', 'fru', 63, 1, 16, 0.2, 'puñado', 100, '🍒'],
  ['Dátiles', 'fru', 282, 2.5, 75, 0.4, 'dátil', 24, '🌴'],
  ['Higos', 'fru', 74, 0.8, 19, 0.3, 'higo', 50, '🫐'],
  ['Papaya', 'fru', 43, 0.5, 11, 0.3, 'ración', 150, '🍈'],
  ['Limón', 'fru', 29, 1.1, 9, 0.3, 'limón', 60, '🍋'],

  // ---- Grasas y frutos secos ----
  ['Aceite de oliva virgen extra', 'gra', 884, 0, 0, 100, 'cucharada', 10, '🫒'],
  ['Almendras', 'gra', 579, 21, 22, 50, 'puñado', 30, '🥜'],
  ['Nueces', 'gra', 654, 15, 14, 65, 'puñado', 30, '🥜'],
  ['Anacardos', 'gra', 553, 18, 30, 44, 'puñado', 30, '🥜'],
  ['Cacahuetes naturales', 'gra', 567, 26, 16, 49, 'puñado', 30, '🥜'],
  ['Pistachos', 'gra', 560, 20, 28, 45, 'puñado', 30, '🥜'],
  ['Avellanas', 'gra', 628, 15, 17, 61, 'puñado', 30, '🌰'],
  ['Crema de cacahuete 100%', 'gra', 598, 25, 20, 50, 'cucharada', 16, '🥜'],
  ['Semillas de chía', 'gra', 486, 17, 42, 31, 'cucharada', 12, '🌱'],
  ['Semillas de lino', 'gra', 534, 18, 29, 42, 'cucharada', 10, '🌱'],
  ['Semillas de calabaza', 'gra', 559, 30, 11, 49, 'cucharada', 10, '🌱'],
  ['Mantequilla', 'gra', 717, 0.9, 0.1, 81, 'porción', 10, '🧈'],
  ['Chocolate negro 85%', 'gra', 590, 10, 19, 46, 'onza', 10, '🍫'],
  ['Cacao puro en polvo', 'gra', 228, 20, 58, 14, 'cucharada', 8, '🍫'],

  // ---- Otros ----
  ['Miel', 'otr', 304, 0.3, 82, 0, 'cucharadita', 7, '🍯'],
  ['Mermelada', 'otr', 250, 0.4, 60, 0, 'cucharada', 15, '🍓'],
  ['Café solo', 'otr', 1, 0.1, 0, 0, 'taza', 50, '☕'],
  ['Tomate frito', 'otr', 80, 1.5, 10, 4, 'ración', 50, '🍅'],
  ['Salsa de soja', 'otr', 53, 8, 5, 0.6, 'cucharada', 15, '🥢'],
  ['Mostaza', 'otr', 66, 4, 5, 4, 'cucharadita', 5, '🌭'],
  ['Vinagre balsámico', 'otr', 88, 0.5, 17, 0, 'cucharada', 15, '🍇'],
  ['Caldo de verduras', 'otr', 5, 0.2, 0.8, 0.1, 'taza', 250, '🍲'],
  // ---- añadidos v3 ----
  ['Creatina monohidrato', 'otr', 0, 0, 0, 0, 'dosis', 5, '💪'],
  ['Proteína de caseína (polvo)', 'prot', 360, 80, 8, 2, 'scoop', 30, '🥤'],
  ['Atún fresco (crudo)', 'prot', 108, 23, 0, 1, 'filete', 150, '🐟'],
  ['Tofu sedoso', 'prot', 55, 4.8, 2, 2.7, 'ración', 100, '🧈'],
  ['Agua de coco', 'lact', 19, 0.7, 3.7, 0.2, 'vaso', 250, '🥥'],
  ['Leche de coco light', 'lact', 70, 0.5, 2, 7, 'ración', 100, '🥥'],
  ['Queso parmesano', 'lact', 431, 38, 4, 29, 'cucharada', 10, '🧀'],
  ['Harina de avena', 'cer', 375, 13, 60, 7, 'cucharada', 10, '🌾'],
  ['Tortilla de maíz', 'cer', 218, 5.7, 45, 2.9, 'tortilla', 30, '🌮'],
  ['Pan de pita integral', 'cer', 266, 9.8, 55, 1.7, 'pita', 60, '🫓'],
  ['Pimiento verde', 'ver', 20, 0.9, 4.6, 0.2, 'pimiento', 120, '🫑'],
  ['Jengibre fresco', 'ver', 80, 1.8, 18, 0.8, 'trozo', 5, '🫚'],
  ['Albahaca fresca', 'ver', 23, 3, 2.6, 0.6, 'puñado', 5, '🌿'],
  ['Alga nori', 'ver', 35, 6, 5, 0.3, 'hoja', 3, '🌿'],
  ['Mantequilla de almendra', 'gra', 614, 21, 19, 56, 'cucharada', 16, '🥜'],
  ['Semillas de sésamo', 'gra', 573, 17.7, 23, 49.7, 'cucharadita', 5, '🌱'],
  ['Canela', 'otr', 247, 4, 81, 1.2, 'pizca', 2, '🌿'],
  ['Hielo', 'otr', 0, 0, 0, 0, 'cubito', 10, '🧊']
];

const FOODS = FOOD_ROWS.map((r, i) => ({
  id: 'f' + i, name: r[0], cat: r[1], kcal: r[2], p: r[3], c: r[4], f: r[5],
  unit: r[6] || null, ug: r[7] || null, emoji: r[8] || CATS[r[1]].e
}));
const FOOD_BY_NAME = Object.fromEntries(FOODS.map(f => [f.name, f]));

/* =====================================================================
   Platos (macros calculados automáticamente desde los ingredientes)
   type: desayuno | snack | comida | cena | batido
   tags: hp = alta proteína, lc = bajo en hidratos, veg = vegetariano, vgn = vegano
   ===================================================================== */
const DISH_ROWS = [
  // ---------- DESAYUNOS ----------
  { n: 'Bowl de avena, plátano y whey', e: '🥣', type: 'desayuno', tags: ['hp', 'veg'], min: 8,
    ing: [['Avena en copos (cruda)', 50], ['Leche semidesnatada', 200], ['Plátano', 120], ['Proteína whey (polvo)', 30], ['Semillas de chía', 10]],
    steps: ['Calienta la leche con la avena a fuego medio 3-4 minutos, removiendo hasta que espese.', 'Retira del fuego y deja templar un minuto; añade el whey y mezcla bien para que no se formen grumos.', 'Pasa a un bol, añade el plátano en rodajas y espolvorea las semillas de chía.'] },
  { n: 'Tostada integral con aguacate y huevos', e: '🥑', type: 'desayuno', tags: ['veg'], min: 10,
    ing: [['Pan integral', 60], ['Aguacate', 70], ['Huevo entero', 110], ['Tomate', 60]],
    steps: ['Tuesta el pan.', 'Aplasta el aguacate con un tenedor, sazona con sal, pimienta y unas gotas de limón.', 'Cocina los huevos pochados o a la plancha con unas gotas de aceite.', 'Monta: pan, aguacate, rodajas de tomate y los huevos encima.'] },
  { n: 'Tortilla de claras con espinacas y pavo', e: '🍳', type: 'desayuno', tags: ['hp'], min: 10,
    ing: [['Clara de huevo', 165], ['Huevo entero', 55], ['Espinacas', 60], ['Fiambre de pavo', 40], ['Aceite de oliva virgen extra', 5], ['Pan integral', 60]],
    steps: ['Saltea las espinacas 1 minuto con el aceite y el pavo troceado.', 'Bate las claras con el huevo, sal y pimienta y viértelas en la sartén.', 'Cuaja a fuego medio-bajo, dobla la tortilla y sirve con el pan tostado.'] },
  { n: 'Skyr con frutos rojos, avena y nueces', e: '🫐', type: 'desayuno', tags: ['hp', 'veg'], min: 3,
    ing: [['Skyr natural', 200], ['Frutos rojos (mezcla)', 100], ['Avena en copos (cruda)', 30], ['Nueces', 15], ['Miel', 7]],
    steps: ['Pon el skyr en un bol.', 'Añade los frutos rojos, la avena y las nueces troceadas.', 'Termina con el hilo de miel.'] },
  { n: 'Pancakes de avena y plátano', e: '🥞', type: 'desayuno', tags: ['veg'], min: 15,
    ing: [['Avena en copos (cruda)', 60], ['Plátano', 120], ['Huevo entero', 110], ['Leche semidesnatada', 50], ['Miel', 7]],
    steps: ['Tritura la avena, el plátano, los huevos y la leche hasta obtener una masa fina.', 'Calienta una sartén antiadherente y vierte pequeñas porciones de masa.', 'Dora 2 minutos por cada lado.', 'Sirve con la miel por encima.'] },
  { n: 'Tostadas de pavo, tomate y AOVE', e: '🍞', type: 'desayuno', tags: ['hp'], min: 5,
    ing: [['Pan integral', 90], ['Fiambre de pavo', 60], ['Tomate', 100], ['Aceite de oliva virgen extra', 8], ['Kiwi', 75]],
    steps: ['Tuesta el pan.', 'Ralla o machaca el tomate y repártelo sobre las tostadas con el aceite.', 'Añade el fiambre de pavo y acompaña con el kiwi.'] },
  { n: 'Porridge de cacao con crema de cacahuete', e: '🍫', type: 'desayuno', tags: ['veg'], min: 8,
    ing: [['Avena en copos (cruda)', 50], ['Bebida de avena', 250], ['Cacao puro en polvo', 8], ['Crema de cacahuete 100%', 16], ['Plátano', 80]],
    steps: ['Cuece la avena con la bebida y el cacao 4-5 minutos a fuego medio.', 'Sirve en un bol con la crema de cacahuete en el centro.', 'Añade el plátano en rodajas.'] },

  // ---------- SNACKS ----------
  { n: 'Yogur griego con miel y nueces', e: '🥣', type: 'snack', tags: ['hp', 'veg'], min: 2,
    ing: [['Yogur griego 0%', 170], ['Nueces', 20], ['Miel', 7]],
    steps: ['Sirve el yogur en un bol.', 'Añade las nueces troceadas y la miel.'] },
  { n: 'Tortitas de arroz con crema de cacahuete y plátano', e: '🍘', type: 'snack', tags: ['vgn', 'veg'], min: 3,
    ing: [['Tortita de arroz', 27], ['Crema de cacahuete 100%', 20], ['Plátano', 100]],
    steps: ['Unta cada tortita con crema de cacahuete.', 'Cubre con rodajas finas de plátano.'] },
  { n: 'Hummus con bastones de verdura', e: '🥕', type: 'snack', tags: ['vgn', 'veg'], min: 5,
    ing: [['Hummus', 75], ['Zanahoria', 100], ['Pepino', 100], ['Pimiento rojo', 80]],
    steps: ['Corta la zanahoria, el pepino y el pimiento en bastones.', 'Sirve con el hummus para mojar.'] },
  { n: 'Batido de proteína con plátano y cacao', e: '🥤', type: 'snack', tags: ['hp', 'veg'], min: 3,
    ing: [['Proteína whey (polvo)', 30], ['Leche semidesnatada', 250], ['Plátano', 120], ['Cacao puro en polvo', 5]],
    steps: ['Pon todos los ingredientes en la batidora.', 'Tritura 30 segundos y bebe al momento (añade hielo si lo prefieres frío).'] },
  { n: 'Queso cottage con piña y chía', e: '🍍', type: 'snack', tags: ['hp', 'veg'], min: 3,
    ing: [['Queso cottage', 180], ['Piña', 120], ['Semillas de chía', 6]],
    steps: ['Pon el queso cottage en un bol.', 'Añade la piña en dados y las semillas de chía.'] },
  { n: 'Huevos duros con tomate', e: '🥚', type: 'snack', tags: ['hp', 'lc', 'veg'], min: 12,
    ing: [['Huevo entero', 110], ['Tomate', 150], ['Aceite de oliva virgen extra', 5], ['Pan integral', 30]],
    steps: ['Cuece los huevos 10 minutos en agua hirviendo y enfría en agua fría.', 'Pela, parte por la mitad y sirve con el tomate aliñado con aceite y sal.', 'Acompaña con el pan.'] },
  { n: 'Manzana con almendras y chocolate negro', e: '🍎', type: 'snack', tags: ['vgn', 'veg'], min: 2,
    ing: [['Manzana', 180], ['Almendras', 20], ['Chocolate negro 85%', 10]],
    steps: ['Corta la manzana en gajos.', 'Sirve con las almendras y el chocolate negro.'] },
  { n: 'Tortitas de arroz con atún y tomate', e: '🐟', type: 'snack', tags: ['hp'], min: 5,
    ing: [['Atún al natural (lata)', 104], ['Tortita de arroz', 27], ['Tomate', 60], ['Aceite de oliva virgen extra', 3]],
    steps: ['Escurre el atún y mézclalo con el aceite y un poco de pimienta.', 'Reparte sobre las tortitas y añade rodajas de tomate.'] },
  { n: 'Kéfir con kiwi y semillas', e: '🥝', type: 'snack', tags: ['veg'], min: 3,
    ing: [['Kéfir natural', 200], ['Kiwi', 75], ['Semillas de calabaza', 10]],
    steps: ['Sirve el kéfir en un vaso o bol.', 'Añade el kiwi en dados y las semillas.'] },

  // ---------- COMIDAS ----------
  { n: 'Pollo a la plancha con arroz integral y brócoli', e: '🍗', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Pechuga de pollo (cruda)', 200], ['Arroz integral (cocido)', 200], ['Brócoli', 200], ['Aceite de oliva virgen extra', 10]],
    steps: ['Cuece el arroz integral (unos 25 minutos) o usa arroz ya cocido.', 'Cuece el brócoli al vapor 5-6 minutos.', 'Sazona el pollo con sal, pimienta, ajo en polvo y pimentón; dóralo en la plancha 5-6 minutos por lado.', 'Sirve todo junto y alíñalo con el aceite crudo.'] },
  { n: 'Pasta integral con ternera y tomate', e: '🍝', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Pasta integral (cocida)', 250], ['Ternera picada magra 5% (cruda)', 150], ['Tomate triturado', 150], ['Cebolla', 60], ['Aceite de oliva virgen extra', 8]],
    steps: ['Cuece la pasta al dente según el envase.', 'Sofríe la cebolla picada con el aceite y añade la carne; deshazla hasta que esté dorada.', 'Añade el tomate triturado, sal y orégano y cuece 10 minutos.', 'Mezcla con la pasta y sirve.'] },
  { n: 'Salmón al horno con boniato y espárragos', e: '🐟', type: 'comida', tags: ['hp'], min: 30,
    ing: [['Salmón (crudo)', 160], ['Boniato (cocido)', 200], ['Espárragos', 150], ['Aceite de oliva virgen extra', 5], ['Limón', 30]],
    steps: ['Precalienta el horno a 200 °C.', 'Corta el boniato en gajos, ponlo en la bandeja con parte del aceite y hornea 15 minutos.', 'Añade los espárragos y el salmón sazonado con sal, pimienta y limón; hornea 12 minutos más.', 'Sirve con un chorrito de limón.'] },
  { n: 'Lentejas estofadas con verduras', e: '🫘', type: 'comida', tags: ['vgn', 'veg'], min: 40,
    ing: [['Lentejas (cocidas)', 300], ['Zanahoria', 80], ['Cebolla', 60], ['Pimiento rojo', 60], ['Tomate triturado', 80], ['Aceite de oliva virgen extra', 10]],
    steps: ['Sofríe la cebolla, el pimiento y la zanahoria picados con el aceite 8 minutos.', 'Añade el tomate, pimentón y comino y cocina 2 minutos.', 'Incorpora las lentejas cocidas con un poco de agua o caldo y cuece 10 minutos a fuego suave.', 'Rectifica de sal y sirve.'] },
  { n: 'Bowl de quinoa, pollo y aguacate', e: '🥗', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Quinoa (cocida)', 200], ['Pechuga de pollo (cruda)', 150], ['Aguacate', 70], ['Tomate', 100], ['Pepino', 80], ['Aceite de oliva virgen extra', 8]],
    steps: ['Cuece la quinoa 12-15 minutos y escúrrela.', 'Corta el pollo en tiras y dóralo en la plancha con sal y especias.', 'Corta el tomate, el pepino y el aguacate.', 'Monta el bowl con la quinoa de base, el resto encima y el aceite con limón.'] },
  { n: 'Merluza al horno con patata y judías verdes', e: '🐟', type: 'comida', tags: ['hp', 'lc'], min: 35,
    ing: [['Merluza (cruda)', 250], ['Patata (cocida)', 250], ['Judías verdes', 200], ['Aceite de oliva virgen extra', 10], ['Ajo', 4]],
    steps: ['Cuece la patata en rodajas y las judías verdes (15 y 8 minutos).', 'Coloca la merluza en una fuente con aceite, ajo laminado, sal y perejil.', 'Hornea a 190 °C unos 12 minutos.', 'Sirve con las verduras aliñadas.'] },
  { n: 'Salteado de ternera con verduras y arroz', e: '🥩', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Ternera magra / solomillo (crudo)', 160], ['Arroz blanco (cocido)', 200], ['Pimiento rojo', 100], ['Champiñones', 100], ['Cebolla', 60], ['Salsa de soja', 15], ['Aceite de oliva virgen extra', 8]],
    steps: ['Corta la ternera en tiras finas y las verduras en juliana.', 'Saltea la carne a fuego fuerte 2-3 minutos y reserva.', 'Saltea las verduras 5 minutos, devuelve la carne y añade la salsa de soja.', 'Sirve sobre el arroz cocido.'] },
  { n: 'Garbanzos con espinacas y huevo', e: '🥬', type: 'comida', tags: ['veg'], min: 20,
    ing: [['Garbanzos (cocidos)', 250], ['Espinacas', 200], ['Huevo entero', 55], ['Aceite de oliva virgen extra', 10], ['Ajo', 4]],
    steps: ['Dora el ajo laminado en el aceite sin que se queme.', 'Añade las espinacas y saltea hasta que se reduzcan.', 'Incorpora los garbanzos, pimentón y comino y cocina 5 minutos.', 'Cuece un huevo (duro o poché) y colócalo encima.'] },
  { n: 'Bowl burrito de pollo', e: '🌯', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Pechuga de pollo (cruda)', 170], ['Arroz blanco (cocido)', 150], ['Alubias (cocidas)', 120], ['Maíz dulce (lata)', 60], ['Tomate', 100], ['Aguacate', 50], ['Lechuga', 40]],
    steps: ['Sazona el pollo con comino, pimentón y ajo y dóralo en la plancha; córtalo en tiras.', 'Calienta el arroz y las alubias.', 'Monta el bowl: arroz, alubias, pollo, maíz, tomate, lechuga y aguacate.'] },
  { n: 'Pasta con atún y calabacín', e: '🍝', type: 'comida', tags: ['hp'], min: 20,
    ing: [['Pasta (cocida)', 250], ['Atún al natural (lata)', 104], ['Tomate triturado', 120], ['Calabacín', 150], ['Aceite de oliva virgen extra', 8]],
    steps: ['Cuece la pasta al dente.', 'Saltea el calabacín en dados con el aceite 5 minutos.', 'Añade el tomate y el atún escurrido y cocina 5 minutos.', 'Mezcla con la pasta.'] },
  { n: 'Pavo con puré de patata y calabacín', e: '🦃', type: 'comida', tags: ['hp'], min: 30,
    ing: [['Pechuga de pavo (cruda)', 180], ['Patata (cocida)', 250], ['Calabacín', 150], ['Leche semidesnatada', 40], ['Aceite de oliva virgen extra', 8]],
    steps: ['Cuece la patata en cubos 15 minutos y haz un puré con la leche, sal y nuez moscada.', 'Corta el calabacín en rodajas y dóralo en la plancha.', 'Marca el pavo en la plancha 4-5 minutos por lado.', 'Sirve con un chorrito de aceite.'] },
  { n: 'Arroz con gambas y verduras', e: '🦐', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Arroz blanco (cocido)', 220], ['Gambas (crudas)', 200], ['Pimiento rojo', 80], ['Guisantes (cocidos)', 80], ['Aceite de oliva virgen extra', 8], ['Ajo', 4]],
    steps: ['Saltea el ajo y el pimiento en dados con el aceite 4 minutos.', 'Añade las gambas peladas y saltea 2-3 minutos.', 'Incorpora el arroz cocido y los guisantes, pimentón y sal, y saltea 3 minutos más.'] },
  { n: 'Tofu salteado con verduras y arroz integral', e: '🥢', type: 'comida', tags: ['vgn', 'veg', 'hp'], min: 25,
    ing: [['Tofu firme', 200], ['Arroz integral (cocido)', 200], ['Brócoli', 150], ['Zanahoria', 80], ['Salsa de soja', 15], ['Aceite de oliva virgen extra', 8]],
    steps: ['Escurre y prensa el tofu 10 minutos; córtalo en cubos.', 'Dóralo en la sartén con la mitad del aceite hasta que esté crujiente.', 'Saltea el brócoli y la zanahoria en el resto del aceite 5 minutos.', 'Añade el tofu y la salsa de soja y sirve sobre el arroz.'] },
  { n: 'Hamburguesa de ternera con patata al horno', e: '🍔', type: 'comida', tags: ['hp'], min: 35,
    ing: [['Ternera picada magra 5% (cruda)', 150], ['Patata (cocida)', 250], ['Lechuga', 40], ['Tomate', 80], ['Aceite de oliva virgen extra', 8]],
    steps: ['Corta la patata en gajos, aliña con aceite y especias y hornea a 200 °C 25 minutos.', 'Forma la hamburguesa con la carne, sal y pimienta.', 'Cocínala en la plancha 4 minutos por lado.', 'Sirve con la ensalada de lechuga y tomate.'] },
  { n: 'Lomo de cerdo con calabaza y ensalada', e: '🥩', type: 'comida', tags: ['hp'], min: 30,
    ing: [['Lomo de cerdo (crudo)', 170], ['Calabaza', 250], ['Lechuga', 60], ['Tomate', 80], ['Aceite de oliva virgen extra', 10]],
    steps: ['Corta la calabaza en cubos y hornéala a 200 °C 20 minutos con parte del aceite.', 'Dora el lomo en la plancha 4-5 minutos por lado.', 'Prepara la ensalada y alíñala con el resto del aceite.'] },
  { n: 'Tempeh con quinoa y verduras', e: '🌱', type: 'comida', tags: ['vgn', 'veg', 'hp'], min: 25,
    ing: [['Tempeh', 150], ['Quinoa (cocida)', 180], ['Espinacas', 100], ['Pimiento rojo', 100], ['Aceite de oliva virgen extra', 8]],
    steps: ['Corta el tempeh en láminas y dóralo en la sartén.', 'Saltea el pimiento y las espinacas 4 minutos.', 'Sirve sobre la quinoa con un chorrito de limón y salsa de soja.'] },
  { n: 'Pulpo con patata y pimentón', e: '🐙', type: 'comida', tags: ['hp', 'lc'], min: 20,
    ing: [['Pulpo (cocido)', 200], ['Patata (cocida)', 200], ['Aceite de oliva virgen extra', 10]],
    steps: ['Cuece las patatas en rodajas.', 'Calienta el pulpo cocido en rodajas.', 'Monta sobre la patata, añade aceite, pimentón y sal gruesa.'] },

  // ---------- CENAS ----------
  { n: 'Tortilla francesa de 3 huevos con ensalada', e: '🍳', type: 'cena', tags: ['hp', 'veg'], min: 10,
    ing: [['Huevo entero', 165], ['Aceite de oliva virgen extra', 5], ['Lechuga', 80], ['Tomate', 120], ['Pepino', 80], ['Pan integral', 60]],
    steps: ['Bate los huevos con sal.', 'Cuaja la tortilla en una sartén con el aceite, dóblala y sirve.', 'Acompaña con la ensalada y el pan integral.'] },
  { n: 'Ensalada completa de atún, huevo y aguacate', e: '🥗', type: 'cena', tags: ['hp', 'lc'], min: 12,
    ing: [['Atún al natural (lata)', 104], ['Huevo entero', 110], ['Aguacate', 70], ['Lechuga', 100], ['Tomate', 120], ['Maíz dulce (lata)', 40], ['Aceite de oliva virgen extra', 10]],
    steps: ['Cuece los huevos 10 minutos.', 'Trocea la lechuga, el tomate y el aguacate.', 'Añade el atún escurrido, el maíz y los huevos en cuartos.', 'Aliña con aceite, vinagre y sal.'] },
  { n: 'Crema de calabacín con pollo desmenuzado', e: '🍲', type: 'cena', tags: ['hp', 'lc'], min: 25,
    ing: [['Calabacín', 300], ['Patata (cocida)', 100], ['Cebolla', 50], ['Pechuga de pollo (cruda)', 150], ['Aceite de oliva virgen extra', 8]],
    steps: ['Pocha la cebolla con el aceite y añade el calabacín y la patata en trozos; cubre con agua y cuece 15 minutos.', 'Tritura hasta obtener una crema fina.', 'Cuece o plancha el pollo, desmenúzalo y colócalo sobre la crema.'] },
  { n: 'Dorada al horno con verduras', e: '🐟', type: 'cena', tags: ['hp'], min: 35,
    ing: [['Dorada (cruda)', 250], ['Patata (cocida)', 150], ['Pimiento rojo', 100], ['Cebolla', 60], ['Calabacín', 100], ['Aceite de oliva virgen extra', 10]],
    steps: ['Corta las verduras y la patata en láminas y colócalas en la bandeja.', 'Pon la dorada limpia encima, con sal, limón y aceite.', 'Hornea a 190 °C unos 25 minutos.'] },
  { n: 'Revuelto de champiñones y gambas', e: '🍄', type: 'cena', tags: ['hp'], min: 15,
    ing: [['Huevo entero', 110], ['Gambas (crudas)', 120], ['Champiñones', 150], ['Ajo', 4], ['Aceite de oliva virgen extra', 8], ['Pan integral', 60]],
    steps: ['Saltea el ajo y los champiñones laminados 5 minutos.', 'Añade las gambas peladas y cocina 2 minutos.', 'Incorpora los huevos batidos y remueve hasta que cuajen jugosos.', 'Sirve con el pan integral.'] },
  { n: 'Sándwich integral de pavo y queso fresco', e: '🥪', type: 'cena', tags: ['hp'], min: 7,
    ing: [['Pan integral', 90], ['Fiambre de pavo', 60], ['Queso fresco (Burgos)', 50], ['Tomate', 80], ['Lechuga', 30]],
    steps: ['Tuesta ligeramente el pan.', 'Monta con el queso fresco, el pavo, el tomate y la lechuga.', 'Cierra y córtalo por la mitad.'] },
  { n: 'Wrap de pollo y verduras', e: '🌯', type: 'cena', tags: ['hp'], min: 15,
    ing: [['Tortilla de trigo (wrap)', 120], ['Pechuga de pollo (cruda)', 130], ['Lechuga', 40], ['Tomate', 60], ['Yogur griego 0%', 40]],
    steps: ['Corta el pollo en tiras y dóralo en la plancha con especias.', 'Calienta los wraps 20 segundos por lado.', 'Rellena con pollo, lechuga, tomate y yogur como salsa; enrolla.'] },
  { n: 'Bacalao con tomate y pimientos', e: '🐟', type: 'cena', tags: ['hp', 'lc'], min: 30,
    ing: [['Bacalao fresco (crudo)', 250], ['Tomate triturado', 150], ['Pimiento rojo', 100], ['Cebolla', 60], ['Patata (cocida)', 150], ['Aceite de oliva virgen extra', 10]],
    steps: ['Sofríe la cebolla y el pimiento 8 minutos.', 'Añade el tomate y cocina 5 minutos más.', 'Coloca el bacalao encima, tapa y cuece 8 minutos.', 'Sirve con la patata cocida.'] },
  { n: 'Tofu al curry con verduras', e: '🍛', type: 'cena', tags: ['vgn', 'veg', 'hp'], min: 25,
    ing: [['Tofu firme', 200], ['Calabacín', 150], ['Pimiento rojo', 100], ['Bebida de soja sin azúcar', 100], ['Aceite de oliva virgen extra', 8], ['Arroz blanco (cocido)', 120]],
    steps: ['Dora el tofu en cubos con el aceite.', 'Añade las verduras troceadas y saltea 5 minutos.', 'Agrega curry en polvo y la bebida de soja y cuece 5 minutos.', 'Sirve con el arroz.'] },
  { n: 'Merluza a la plancha con puré de coliflor', e: '🐟', type: 'cena', tags: ['hp', 'lc'], min: 25,
    ing: [['Merluza (cruda)', 250], ['Coliflor', 250], ['Patata (cocida)', 80], ['Aceite de oliva virgen extra', 10]],
    steps: ['Cuece la coliflor y la patata 15 minutos y tritúralas con parte del aceite y sal.', 'Marca la merluza en la plancha 3-4 minutos por lado.', 'Sirve sobre el puré con un chorrito de aceite y limón.'] },
  { n: 'Ensalada templada de garbanzos y atún', e: '🥗', type: 'cena', tags: ['hp'], min: 10,
    ing: [['Garbanzos (cocidos)', 200], ['Atún al natural (lata)', 104], ['Tomate', 100], ['Cebolla', 40], ['Rúcula', 30], ['Aceite de oliva virgen extra', 10]],
    steps: ['Calienta ligeramente los garbanzos.', 'Mezcla con el atún, el tomate, la cebolla picada y la rúcula.', 'Aliña con aceite, vinagre y sal.'] },

  // ================= v3: BATIDOS DE PROTEÍNA =================
  { n: 'Batido post-entreno con creatina', e: '🥤', type: 'batido', tags: ['hp', 'veg'], min: 3, look: 'shake', color: '#E9D3B0',
    ing: [['Leche semidesnatada', 250], ['Proteína whey (polvo)', 30], ['Plátano', 120], ['Avena en copos (cruda)', 30], ['Creatina monohidrato', 5]],
    steps: ['Pon la leche en la batidora y añade el resto de ingredientes.', 'Tritura 30-40 segundos hasta que no queden grumos de avena.', 'Tómalo en la hora siguiente al entrenamiento. La creatina funciona por toma diaria constante (3-5 g), no por el momento exacto.'] },
  { n: 'Batido de chocolate y cacahuete', e: '🍫', type: 'batido', tags: ['hp', 'veg'], min: 3, look: 'shake', color: '#7B4B2A',
    ing: [['Bebida de almendras sin azúcar', 300], ['Proteína whey (polvo)', 30], ['Cacao puro en polvo', 8], ['Crema de cacahuete 100%', 16], ['Hielo', 50]],
    steps: ['Añade la bebida de almendras, el whey, el cacao y la crema de cacahuete a la batidora.', 'Agrega el hielo y tritura hasta que quede espumoso.', 'Sabe a batido de tienda con muy poco azúcar.'] },
  { n: 'Frappé de café proteico', e: '☕', type: 'batido', tags: ['hp', 'veg'], min: 4, look: 'shake', color: '#C8A27A',
    ing: [['Café solo', 100], ['Leche desnatada', 200], ['Proteína whey (polvo)', 30], ['Hielo', 80], ['Canela', 1]],
    steps: ['Prepara el café y déjalo enfriar (o usa café frío).', 'Tritura el café con la leche, el whey y el hielo.', 'Sirve con canela por encima. Ideal como desayuno rápido o antes de entrenar.'] },
  { n: 'Batido de frutos rojos y skyr', e: '🍓', type: 'batido', tags: ['hp', 'veg'], min: 3, look: 'shake', color: '#E07A9A',
    ing: [['Skyr natural', 150], ['Frutos rojos (mezcla)', 120], ['Leche desnatada', 150], ['Miel', 7]],
    steps: ['Pon los frutos rojos (pueden ser congelados) en la batidora.', 'Añade el skyr, la leche y la miel.', 'Tritura hasta que quede cremoso.'] },
  { n: 'Batido tropical de mango y coco', e: '🥭', type: 'batido', tags: ['hp', 'veg'], min: 3, look: 'shake', color: '#FFC24A',
    ing: [['Agua de coco', 250], ['Mango', 150], ['Proteína whey (polvo)', 30], ['Limón', 15], ['Hielo', 40]],
    steps: ['Pela y trocea el mango.', 'Tritura con el agua de coco, el whey, el zumo de limón y el hielo.', 'Muy refrescante e hidratante para días de calor o tras el cardio.'] },
  { n: 'Batido verde proteico', e: '🥬', type: 'batido', tags: ['hp', 'vgn', 'veg'], min: 4, look: 'shake', color: '#8CCB5E',
    ing: [['Agua de coco', 200], ['Espinacas', 40], ['Plátano', 100], ['Manzana', 100], ['Proteína vegetal (polvo)', 30], ['Jengibre fresco', 3]],
    steps: ['Tritura primero las espinacas con el agua de coco para que no queden hebras.', 'Añade el plátano, la manzana troceada, la proteína y el jengibre.', 'Tritura de nuevo. Aporta vitamina C, hierro y potasio.'] },
  { n: 'Batido de tarta de manzana', e: '🍏', type: 'batido', tags: ['hp', 'veg'], min: 4, look: 'shake', color: '#EBD9A8',
    ing: [['Yogur griego 0%', 150], ['Manzana', 150], ['Avena en copos (cruda)', 30], ['Leche semidesnatada', 150], ['Proteína whey (polvo)', 20], ['Canela', 2]],
    steps: ['Trocea la manzana (con piel aporta más fibra).', 'Tritura con el yogur, la avena, la leche, el whey y la canela.', 'Sabe a tarta de manzana y sacia muchísimo.'] },
  { n: 'Batido nocturno de caseína', e: '🌙', type: 'batido', tags: ['hp', 'veg'], min: 2, look: 'shake', color: '#B98E6B',
    ing: [['Leche desnatada', 250], ['Proteína de caseína (polvo)', 30], ['Mantequilla de almendra', 10], ['Cacao puro en polvo', 5]],
    steps: ['Mezcla todo en un vaso o en la batidora.', 'La caseína se digiere despacio: es ideal antes de dormir para recuperar durante la noche.'] },
  { n: 'Batido vegano de chocolate y dátiles', e: '🌴', type: 'batido', tags: ['hp', 'vgn', 'veg'], min: 4, look: 'shake', color: '#6E4A33',
    ing: [['Bebida de soja sin azúcar', 300], ['Proteína vegetal (polvo)', 30], ['Dátiles', 24], ['Cacao puro en polvo', 8], ['Plátano', 80]],
    steps: ['Quita el hueso al dátil.', 'Tritura todo hasta que el dátil quede completamente deshecho.', 'El dátil endulza sin azúcar añadido.'] },
  { n: 'Batido para ganar masa', e: '💪', type: 'batido', tags: ['hp', 'veg'], min: 4, look: 'shake', color: '#D9B88F',
    ing: [['Leche semidesnatada', 400], ['Avena en copos (cruda)', 60], ['Plátano', 120], ['Crema de cacahuete 100%', 32], ['Proteína whey (polvo)', 30], ['Miel', 14], ['Creatina monohidrato', 5]],
    steps: ['Tritura la avena sola unos segundos para hacerla harina.', 'Añade el resto y tritura hasta que quede homogéneo.', 'Unas 900 kcal en un vaso: perfecto si te cuesta llegar a tus calorías en volumen.'] },

  // ================= v3: SMOOTHIES VITAMÍNICOS =================
  { n: 'Smoothie antioxidante de frutos rojos y kéfir', e: '🫐', type: 'batido', tags: ['veg'], min: 3, look: 'shake', color: '#8E4F9E',
    ing: [['Kéfir natural', 200], ['Frutos rojos (mezcla)', 150], ['Arándanos', 50], ['Semillas de chía', 10]],
    steps: ['Tritura el kéfir con los frutos rojos y los arándanos.', 'Añade la chía, remueve y deja reposar 5 minutos para que espese.', 'Rico en antioxidantes, vitamina C y probióticos.'] },
  { n: 'Smoothie tropical de vitamina C', e: '🍍', type: 'batido', tags: ['vgn', 'veg'], min: 4, look: 'shake', color: '#FFB238',
    ing: [['Piña', 120], ['Mango', 100], ['Naranja', 150], ['Agua de coco', 150], ['Jengibre fresco', 3]],
    steps: ['Pela la naranja y trocea la fruta.', 'Tritura todo con el agua de coco y el jengibre.', 'Un vaso cubre de sobra la vitamina C del día.'] },
  { n: 'Zumo verde de pepino, manzana y kale', e: '🥒', type: 'batido', tags: ['vgn', 'veg', 'lc'], min: 5, look: 'shake', color: '#9BD27A',
    ing: [['Pepino', 150], ['Manzana', 150], ['Kale / col rizada', 40], ['Limón', 30], ['Jengibre fresco', 5]],
    steps: ['Lava bien todo y trocea el pepino y la manzana.', 'Tritura con el zumo de limón, el jengibre y un poco de agua fría.', 'Si lo quieres más fino, cuélalo (aunque perderás fibra).'] },
  { n: 'Smoothie de kiwi, espinacas y yogur', e: '🥝', type: 'batido', tags: ['veg'], min: 3, look: 'shake', color: '#A8D46F',
    ing: [['Kiwi', 150], ['Espinacas', 40], ['Plátano', 80], ['Yogur natural', 125]],
    steps: ['Pela los kiwis.', 'Tritura con las espinacas, el plátano y el yogur.', 'El kiwi aporta más vitamina C que la naranja.'] },
  { n: 'Smoothie de remolacha y fresa', e: '🍓', type: 'batido', tags: ['veg'], min: 3, look: 'shake', color: '#C2304F',
    ing: [['Remolacha (cocida)', 80], ['Fresas', 150], ['Yogur griego 0%', 125], ['Miel', 7]],
    steps: ['Trocea la remolacha cocida.', 'Tritura con las fresas, el yogur y la miel.', 'La remolacha aporta nitratos naturales que ayudan al rendimiento en el ejercicio.'] },

  // ================= v3: DULCES Y SNACKS SANOS =================
  { n: 'Mug cake proteico de chocolate', e: '🧁', type: 'snack', tags: ['hp', 'veg'], min: 4, look: 'bowl',
    ing: [['Huevo entero', 55], ['Proteína whey (polvo)', 30], ['Harina de avena', 20], ['Cacao puro en polvo', 8], ['Leche semidesnatada', 30], ['Chocolate negro 85%', 10]],
    steps: ['Bate el huevo con la leche en una taza grande.', 'Añade el whey, la harina de avena y el cacao, y mezcla sin grumos.', 'Pon la onza de chocolate en el centro y cocina en el microondas 60-75 segundos.', 'Deja reposar un minuto: queda esponjoso y con el centro fundido.'] },
  { n: 'Helado de plátano y cacao (nice cream)', e: '🍨', type: 'snack', tags: ['vgn', 'veg'], min: 5, look: 'bowl',
    ing: [['Plátano', 200], ['Cacao puro en polvo', 8], ['Crema de cacahuete 100%', 10]],
    steps: ['Trocea el plátano y congélalo al menos 4 horas.', 'Tritura el plátano congelado con el cacao hasta que tenga textura de helado.', 'Sirve con la crema de cacahuete por encima. Sin azúcar añadido.'] },
  { n: 'Tortitas proteicas de claras y avena', e: '🥞', type: 'desayuno', tags: ['hp', 'veg'], min: 12,
    ing: [['Clara de huevo', 165], ['Harina de avena', 40], ['Plátano', 60], ['Canela', 1], ['Frutos rojos (mezcla)', 60]],
    steps: ['Tritura las claras con la harina de avena, el plátano y la canela.', 'Haz tortitas pequeñas en una sartén antiadherente a fuego medio.', 'Dales la vuelta cuando salgan burbujas.', 'Sirve con los frutos rojos por encima.'] },
  { n: 'Overnight oats de tarta de queso y fresa', e: '🍓', type: 'desayuno', tags: ['hp', 'veg'], min: 5, look: 'bowl',
    ing: [['Avena en copos (cruda)', 50], ['Yogur griego 0%', 125], ['Leche semidesnatada', 100], ['Fresas', 100], ['Semillas de chía', 8], ['Miel', 7]],
    steps: ['Mezcla en un tarro la avena, el yogur, la leche, la chía y la miel.', 'Cubre con las fresas troceadas.', 'Déjalo en la nevera toda la noche: por la mañana está listo y sabe a tarta de queso.'] },
  { n: 'Yogur helado de frutos rojos y chocolate', e: '🍫', type: 'snack', tags: ['hp', 'veg'], min: 10,
    ing: [['Yogur griego 0%', 250], ['Frutos rojos (mezcla)', 100], ['Chocolate negro 85%', 10], ['Miel', 7]],
    steps: ['Mezcla el yogur con la miel y extiéndelo en una bandeja con papel de horno.', 'Reparte los frutos rojos y el chocolate rallado por encima.', 'Congela 2 horas y rómpelo en trozos como una tableta.'] },
  { n: 'Bolitas energéticas de dátil y cacao', e: '🌰', type: 'snack', tags: ['vgn', 'veg'], min: 15,
    ing: [['Dátiles', 72], ['Almendras', 30], ['Avena en copos (cruda)', 20], ['Cacao puro en polvo', 8]],
    steps: ['Tritura las almendras y la avena hasta que queden casi harina.', 'Añade los dátiles sin hueso y el cacao y tritura hasta formar una masa.', 'Haz 4 bolitas con las manos y guárdalas en la nevera. Perfectas antes de entrenar.'] },
  { n: 'Manzana asada con canela y yogur', e: '🍎', type: 'snack', tags: ['veg'], min: 25, look: 'bowl',
    ing: [['Manzana', 180], ['Canela', 2], ['Yogur griego 0%', 125], ['Nueces', 10]],
    steps: ['Descorazona la manzana, espolvorea la canela y hornéala a 190 °C unos 20 minutos (o 4 minutos en el microondas).', 'Sírvela templada sobre el yogur.', 'Termina con las nueces troceadas.'] },
  { n: 'Garbanzos crujientes con pimentón', e: '🫘', type: 'snack', tags: ['vgn', 'veg'], min: 30, look: 'bowl',
    ing: [['Garbanzos (cocidos)', 150], ['Aceite de oliva virgen extra', 5]],
    steps: ['Seca muy bien los garbanzos cocidos con papel de cocina.', 'Mézclalos con el aceite, pimentón, comino y sal.', 'Hornea a 200 °C unos 25 minutos, moviéndolos a mitad. Un snack crujiente y saciante.'] },

  // ================= v3: COMIDAS =================
  { n: 'Poke bowl de salmón', e: '🍣', type: 'comida', tags: ['hp'], min: 20, look: 'bowl',
    ing: [['Arroz blanco (cocido)', 150], ['Salmón (crudo)', 120], ['Edamame', 60], ['Aguacate', 50], ['Pepino', 60], ['Mango', 60], ['Salsa de soja', 15], ['Semillas de sésamo', 5]],
    steps: ['Usa salmón apto para consumo en crudo (congelado previamente) y córtalo en dados.', 'Monta el bowl con el arroz de base y coloca encima el salmón, el edamame, el aguacate, el pepino y el mango.', 'Aliña con la salsa de soja y espolvorea el sésamo.'] },
  { n: 'Tacos de pollo con pico de gallo', e: '🌮', type: 'comida', tags: ['hp'], min: 20,
    ing: [['Tortilla de maíz', 90], ['Pechuga de pollo (cruda)', 150], ['Tomate', 100], ['Cebolla', 30], ['Aguacate', 50], ['Limón', 10]],
    steps: ['Sazona el pollo con comino, pimentón y ajo y hazlo a la plancha; córtalo en tiras.', 'Pica el tomate y la cebolla, y mézclalos con el zumo de limón y sal (pico de gallo).', 'Calienta las tortillas y rellénalas con el pollo, el pico de gallo y el aguacate.'] },
  { n: 'Curry ligero de garbanzos y espinacas', e: '🍛', type: 'comida', tags: ['vgn', 'veg'], min: 25,
    ing: [['Garbanzos (cocidos)', 200], ['Espinacas', 100], ['Tomate triturado', 100], ['Leche de coco light', 80], ['Cebolla', 50], ['Arroz blanco (cocido)', 120], ['Aceite de oliva virgen extra', 5]],
    steps: ['Sofríe la cebolla con el aceite y 1 cucharadita de curry en polvo.', 'Añade el tomate y la leche de coco y cuece 5 minutos.', 'Incorpora los garbanzos y las espinacas y cocina 5 minutos más.', 'Sirve con el arroz.'] },
  { n: 'Hamburguesa de salmón con rúcula', e: '🍔', type: 'comida', tags: ['hp'], min: 20,
    ing: [['Salmón (crudo)', 140], ['Pan integral', 70], ['Rúcula', 20], ['Tomate', 60], ['Yogur griego 0%', 30]],
    steps: ['Pica el salmón a cuchillo, sazónalo y forma una hamburguesa.', 'Hazla a la plancha 3 minutos por lado.', 'Mezcla el yogur con limón y eneldo como salsa.', 'Monta en el pan tostado con la rúcula y el tomate.'] },
  { n: 'Shakshuka (huevos en salsa de tomate)', e: '🍳', type: 'comida', tags: ['veg'], min: 25,
    ing: [['Huevo entero', 110], ['Tomate triturado', 200], ['Pimiento rojo', 80], ['Cebolla', 50], ['Aceite de oliva virgen extra', 8], ['Pan integral', 60]],
    steps: ['Sofríe la cebolla y el pimiento con el aceite, comino y pimentón.', 'Añade el tomate y cuece 10 minutos.', 'Haz dos huecos, casca los huevos y tapa hasta que cuaje la clara (5-6 minutos).', 'Sirve con el pan para mojar.'] },
  { n: 'Buddha bowl de quinoa y boniato asado', e: '🥗', type: 'comida', tags: ['vgn', 'veg'], min: 35, look: 'bowl',
    ing: [['Quinoa (cocida)', 150], ['Boniato (cocido)', 150], ['Garbanzos (cocidos)', 80], ['Kale / col rizada', 40], ['Hummus', 30], ['Aguacate', 40]],
    steps: ['Asa el boniato en dados a 200 °C unos 25 minutos con especias.', 'Masajea el kale con unas gotas de limón para ablandarlo.', 'Monta el bowl con la quinoa, el boniato, los garbanzos, el kale y el aguacate, y corona con el hummus.'] },
  { n: 'Wok de pollo teriyaki casero', e: '🥢', type: 'comida', tags: ['hp'], min: 25,
    ing: [['Pechuga de pollo (cruda)', 160], ['Arroz integral (cocido)', 150], ['Brócoli', 100], ['Pimiento rojo', 80], ['Salsa de soja', 15], ['Miel', 7], ['Jengibre fresco', 3], ['Aceite de oliva virgen extra', 5]],
    steps: ['Mezcla la soja, la miel y el jengibre rallado: es tu salsa teriyaki ligera.', 'Saltea el pollo en tiras a fuego fuerte y reserva.', 'Saltea las verduras 4 minutos, devuelve el pollo y añade la salsa hasta que brille.', 'Sirve sobre el arroz.'] },
  { n: 'Pasta boloñesa de lentejas', e: '🍝', type: 'comida', tags: ['vgn', 'veg'], min: 30,
    ing: [['Pasta integral (cocida)', 200], ['Lentejas (cocidas)', 150], ['Tomate triturado', 150], ['Zanahoria', 50], ['Cebolla', 40], ['Aceite de oliva virgen extra', 8]],
    steps: ['Sofríe la cebolla y la zanahoria muy picadas con el aceite.', 'Añade el tomate y las lentejas y cuece 10 minutos aplastando un poco las lentejas.', 'Mezcla con la pasta. Sabe a boloñesa con mucha más fibra.'] },
  { n: 'Ensalada César fit', e: '🥗', type: 'comida', tags: ['hp', 'lc'], min: 20, look: 'bowl',
    ing: [['Pechuga de pollo (cruda)', 150], ['Lechuga', 120], ['Pan integral', 30], ['Queso parmesano', 10], ['Yogur griego 0%', 50], ['Mostaza', 5], ['Limón', 10]],
    steps: ['Haz el pollo a la plancha y córtalo en tiras.', 'Tuesta el pan en dados para hacer picatostes.', 'Mezcla el yogur, la mostaza, el limón y la mitad del parmesano como salsa César ligera.', 'Monta la lechuga con el pollo, los picatostes, la salsa y el resto del parmesano.'] },
  { n: 'Albóndigas de pavo en salsa de tomate', e: '🍲', type: 'comida', tags: ['hp'], min: 35,
    ing: [['Pechuga de pavo (cruda)', 180], ['Huevo entero', 25], ['Pan integral', 20], ['Tomate triturado', 150], ['Arroz blanco (cocido)', 120], ['Aceite de oliva virgen extra', 5]],
    steps: ['Pica el pavo y mézclalo con el huevo, el pan rallado, ajo, perejil y sal.', 'Forma albóndigas y dóralas con el aceite.', 'Añade el tomate y cuece 15 minutos a fuego suave.', 'Sirve con el arroz.'] },
  { n: 'Gyros de pollo en pita con tzatziki', e: '🥙', type: 'comida', tags: ['hp'], min: 20,
    ing: [['Pan de pita integral', 60], ['Pechuga de pollo (cruda)', 140], ['Yogur griego 0%', 60], ['Pepino', 50], ['Tomate', 60], ['Cebolla', 20]],
    steps: ['Marina el pollo con pimentón, comino, orégano y limón, y hazlo a la plancha en tiras.', 'Ralla el pepino y mézclalo con el yogur, ajo y sal (tzatziki).', 'Rellena la pita caliente con el pollo, el tomate, la cebolla y el tzatziki.'] },

  // ================= v3: CENAS =================
  { n: 'Pizza de tortilla integral', e: '🍕', type: 'cena', tags: ['hp'], min: 15,
    ing: [['Tortilla de trigo (wrap)', 60], ['Tomate triturado', 60], ['Mozzarella light', 60], ['Fiambre de pavo', 40], ['Champiñones', 50], ['Albahaca fresca', 3]],
    steps: ['Unta la tortilla con el tomate y orégano.', 'Reparte la mozzarella, el pavo y los champiñones laminados.', 'Hornea a 220 °C unos 8 minutos hasta que la base esté crujiente.', 'Termina con la albahaca fresca.'] },
  { n: 'Tortilla de patata y calabacín al horno', e: '🥔', type: 'cena', tags: ['veg'], min: 35,
    ing: [['Huevo entero', 165], ['Patata (cocida)', 150], ['Calabacín', 100], ['Cebolla', 40], ['Aceite de oliva virgen extra', 5]],
    steps: ['Cuece o haz al microondas la patata en láminas finas.', 'Sofríe la cebolla y el calabacín con el aceite.', 'Mezcla con los huevos batidos y hornea en un molde a 180 °C unos 20 minutos.', 'Toda la jugosidad con mucho menos aceite.'] },
  { n: 'Revuelto de tofu con espinacas', e: '🥬', type: 'cena', tags: ['vgn', 'veg', 'hp'], min: 15,
    ing: [['Tofu firme', 200], ['Espinacas', 80], ['Champiñones', 80], ['Pan integral', 60], ['Aceite de oliva virgen extra', 5]],
    steps: ['Saltea los champiñones con el aceite.', 'Desmenuza el tofu con un tenedor y añádelo con una pizca de cúrcuma, sal y pimienta.', 'Agrega las espinacas hasta que se reduzcan.', 'Sirve con el pan tostado.'] },
  { n: 'Crema de calabaza y jengibre con huevo poché', e: '🎃', type: 'cena', tags: ['veg', 'lc'], min: 30, look: 'bowl',
    ing: [['Calabaza', 300], ['Zanahoria', 80], ['Jengibre fresco', 3], ['Huevo entero', 55], ['Aceite de oliva virgen extra', 5], ['Semillas de calabaza', 10]],
    steps: ['Cuece la calabaza y la zanahoria con el jengibre 20 minutos y tritura con el aceite.', 'Haz el huevo poché: 3 minutos en agua casi hirviendo con un chorrito de vinagre.', 'Sirve la crema con el huevo encima y las semillas tostadas.'] },
  { n: 'Brochetas de pollo y verduras con salsa de yogur', e: '🍢', type: 'cena', tags: ['hp', 'lc'], min: 25,
    ing: [['Pechuga de pollo (cruda)', 170], ['Pimiento verde', 80], ['Cebolla', 50], ['Calabacín', 80], ['Yogur griego 0%', 60], ['Aceite de oliva virgen extra', 5]],
    steps: ['Corta el pollo y las verduras en dados y monta las brochetas.', 'Úntalas con el aceite y especias y hazlas a la plancha o al horno 12-15 minutos.', 'Sirve con el yogur mezclado con limón, ajo y menta.'] },
  { n: 'Wrap de atún y aguacate', e: '🌯', type: 'cena', tags: ['hp'], min: 8,
    ing: [['Tortilla de trigo (wrap)', 60], ['Atún al natural (lata)', 104], ['Aguacate', 50], ['Lechuga', 30], ['Tomate', 50], ['Yogur griego 0%', 30]],
    steps: ['Mezcla el atún escurrido con el yogur, sal y pimienta.', 'Extiende el aguacate machacado sobre la tortilla.', 'Añade el atún, la lechuga y el tomate y enrolla bien apretado.'] },
  { n: 'Tataki de atún con ensalada de algas', e: '🐟', type: 'cena', tags: ['hp', 'lc'], min: 15,
    ing: [['Atún fresco (crudo)', 150], ['Pepino', 100], ['Edamame', 60], ['Alga nori', 3], ['Salsa de soja', 15], ['Semillas de sésamo', 5]],
    steps: ['Marca el atún 30 segundos por cada lado en una sartén muy caliente y córtalo en lonchas.', 'Mezcla el pepino en tiras con el edamame y el alga nori troceada.', 'Aliña con la soja y el sésamo, y coloca el atún encima.'] },

  // ================= v3: DESAYUNOS =================
  { n: 'Tostada de salmón ahumado, aguacate y huevo', e: '🥑', type: 'desayuno', tags: ['hp'], min: 10,
    ing: [['Pan de centeno', 60], ['Salmón ahumado', 50], ['Aguacate', 50], ['Huevo entero', 55]],
    steps: ['Tuesta el pan de centeno.', 'Unta el aguacate machacado con limón y pimienta.', 'Coloca el salmón ahumado y el huevo poché o a la plancha encima.'] },
  { n: 'Bowl de frutos rojos estilo açaí', e: '🫐', type: 'desayuno', tags: ['veg'], min: 5, look: 'bowl',
    ing: [['Frutos rojos (mezcla)', 150], ['Plátano', 80], ['Yogur griego 0%', 100], ['Muesli sin azúcar', 30], ['Semillas de chía', 8]],
    steps: ['Tritura los frutos rojos congelados con medio plátano y el yogur hasta que quede muy espeso.', 'Sirve en un bol y decora con el resto del plátano, el muesli y la chía.'] },
  { n: 'Crepes de avena rellenos de cottage y fresa', e: '🥞', type: 'desayuno', tags: ['hp', 'veg'], min: 12,
    ing: [['Harina de avena', 40], ['Clara de huevo', 100], ['Leche desnatada', 50], ['Queso cottage', 100], ['Fresas', 80]],
    steps: ['Bate la harina de avena con las claras y la leche hasta obtener una masa líquida.', 'Haz crepes finos en una sartén antiadherente.', 'Rellénalos con el cottage y las fresas laminadas.'] },
  { n: 'Huevos turcos con yogur (çilbir)', e: '🍳', type: 'desayuno', tags: ['hp', 'veg'], min: 12,
    ing: [['Yogur griego natural', 125], ['Huevo entero', 110], ['Aceite de oliva virgen extra', 5], ['Pan de pita integral', 60]],
    steps: ['Mezcla el yogur con un poco de ajo rallado y sal, y extiéndelo en un plato.', 'Haz los huevos poché y colócalos encima.', 'Calienta el aceite con pimentón y riégalo por encima. Moja con el pan de pita.'] },
  { n: 'Porridge de manzana y canela con proteína', e: '🍏', type: 'desayuno', tags: ['hp', 'veg'], min: 8, look: 'bowl',
    ing: [['Avena en copos (cruda)', 50], ['Leche semidesnatada', 200], ['Manzana', 120], ['Canela', 2], ['Proteína whey (polvo)', 20], ['Nueces', 10]],
    steps: ['Cuece la avena con la leche, la manzana rallada y la canela 4-5 minutos.', 'Fuera del fuego, añade el whey y remueve.', 'Termina con las nueces por encima.'] }
];

function dishFromRow(r, i) {
  const items = r.ing.map(([name, g]) => {
    const f = FOOD_BY_NAME[name];
    if (!f) throw new Error('Ingrediente no encontrado: ' + name + ' en ' + r.n);
    return { food: f, g };
  });
  const m = { kcal: 0, p: 0, c: 0, f: 0, g: 0 };
  items.forEach(({ food, g }) => {
    m.kcal += food.kcal * g / 100; m.p += food.p * g / 100;
    m.c += food.c * g / 100; m.f += food.f * g / 100; m.g += g;
  });
  return { id: 'd' + i, name: r.n, emoji: r.e, type: r.type, tags: r.tags, min: r.min, items, steps: r.steps, m, look: r.look || (r.type === 'batido' ? 'shake' : 'plate'), color: r.color || null };
}
const DISHES = DISH_ROWS.map(dishFromRow);

/* =====================================================================
   Deporte
   ===================================================================== */
// MET (Compendium of Physical Activities, valores orientativos)
const ACTIVITIES = [
  { n: 'Caminar a paso ligero (5 km/h)', met: 3.5, e: '🚶' },
  { n: 'Caminar rápido (6,5 km/h)', met: 5.0, e: '🚶' },
  { n: 'Senderismo / caminata en cuesta', met: 6.0, e: '🥾' },
  { n: 'Correr suave (8 km/h)', met: 8.3, e: '🏃' },
  { n: 'Correr (10 km/h)', met: 9.8, e: '🏃' },
  { n: 'Correr rápido (12 km/h)', met: 11.8, e: '🏃' },
  { n: 'Bicicleta suave', met: 5.8, e: '🚴' },
  { n: 'Bicicleta moderada (20 km/h)', met: 8.0, e: '🚴' },
  { n: 'Spinning / bici estática intensa', met: 8.8, e: '🚴' },
  { n: 'Elíptica', met: 5.0, e: '🏃' },
  { n: 'Remo (máquina) moderado', met: 7.0, e: '🚣' },
  { n: 'Natación suave', met: 5.8, e: '🏊' },
  { n: 'Natación intensa', met: 9.8, e: '🏊' },
  { n: 'HIIT / circuito', met: 8.0, e: '🔥' },
  { n: 'Comba', met: 11.0, e: '🪢' },
  { n: 'Subir escaleras', met: 8.8, e: '🪜' },
  { n: 'Entrenamiento de fuerza (moderado)', met: 3.5, e: '🏋️' },
  { n: 'Entrenamiento de fuerza (intenso)', met: 6.0, e: '🏋️' },
  { n: 'Calistenia', met: 4.0, e: '🤸' },
  { n: 'Crossfit / entrenamiento funcional', met: 8.0, e: '🔥' },
  { n: 'Yoga', met: 2.5, e: '🧘' },
  { n: 'Pilates', met: 3.0, e: '🧘' },
  { n: 'Estiramientos / movilidad', met: 2.3, e: '🤸' },
  { n: 'Baile / Zumba', met: 6.0, e: '💃' },
  { n: 'Fútbol', met: 7.0, e: '⚽' },
  { n: 'Pádel / tenis (dobles)', met: 6.0, e: '🎾' },
  { n: 'Baloncesto', met: 6.5, e: '🏀' },
  { n: 'Boxeo / saco', met: 6.0, e: '🥊' },
  { n: 'Artes marciales', met: 10.0, e: '🥋' },
  { n: 'Patinaje', met: 7.0, e: '⛸️' }
];

const MUSCLES = {
  pecho: 'Pecho', espalda: 'Espalda', pierna: 'Pierna', gluteo: 'Glúteo e isquios',
  hombro: 'Hombro', biceps: 'Bíceps', triceps: 'Tríceps', core: 'Core'
};

// [nombre, grupo, lugar(c casa|g gimnasio), tipo(comp|iso), riesgos(rod,hom,esp,mun), consejo, imagen (Free Exercise DB)]
const EX_ROWS = [
  // ----- CASA -----
  ['Flexiones', 'pecho', 'c', 'comp', ['hom', 'mun'], 'Cuerpo en línea, codos a 45° del tronco, baja hasta casi tocar el suelo.', 'Pushups'],
  ['Flexiones inclinadas (manos en silla)', 'pecho', 'c', 'comp', [], 'Versión más fácil: manos en una superficie elevada.', 'Incline_Push-Up'],
  ['Flexiones diamante', 'triceps', 'c', 'comp', ['mun'], 'Manos juntas bajo el pecho, codos pegados al cuerpo.', 'Push-Ups_-_Close_Triceps_Position'],
  ['Fondos de tríceps en silla', 'triceps', 'c', 'comp', ['hom'], 'Espalda cerca de la silla, baja hasta 90° en los codos.', 'Bench_Dips'],
  ['Remo con mochila cargada', 'espalda', 'c', 'comp', ['esp'], 'Torso inclinado con espalda recta, lleva la mochila al ombligo.', 'Bent_Over_Two-Dumbbell_Row'],
  ['Remo invertido bajo una mesa', 'espalda', 'c', 'comp', ['hom'], 'Cuerpo recto, tira del pecho hacia el borde de la mesa.', 'Inverted_Row'],
  ['Superman', 'espalda', 'c', 'iso', [], 'Eleva brazos y piernas a la vez, mantén 2 s arriba.', 'Superman'],
  ['Sentadilla con peso corporal', 'pierna', 'c', 'comp', ['rod'], 'Rodillas alineadas con los pies, baja con el pecho alto.', 'Bodyweight_Squat'],
  ['Sentadilla búlgara', 'pierna', 'c', 'comp', ['rod'], 'Pie trasero apoyado en una silla, baja controlando.', 'Split_Squats'],
  ['Zancadas alternas', 'pierna', 'c', 'comp', ['rod'], 'Paso largo, rodilla delantera sin pasar mucho la punta del pie.', 'Bodyweight_Walking_Lunge'],
  ['Elevación de talones a una pierna', 'pierna', 'c', 'iso', [], 'Sube lento y baja lento, pausa arriba.', 'Standing_Calf_Raises'],
  ['Peso muerto rumano con mochila', 'gluteo', 'c', 'comp', ['esp'], 'Cadera atrás, espalda neutra, piernas casi rectas.', 'Stiff-Legged_Dumbbell_Deadlift'],
  ['Puente de glúteo', 'gluteo', 'c', 'iso', [], 'Aprieta glúteos arriba 2 segundos.', 'Butt_Lift_Bridge'],
  ['Hip thrust con la espalda en el sofá', 'gluteo', 'c', 'comp', [], 'Barbilla al pecho, empuja con los talones.', 'Barbell_Hip_Thrust'],
  ['Press de hombros con mochila o garrafas', 'hombro', 'c', 'comp', ['hom'], 'Core firme, empuja por encima de la cabeza sin arquear la zona lumbar.', 'Dumbbell_Shoulder_Press'],
  ['Elevaciones laterales con botellas', 'hombro', 'c', 'iso', [], 'Codos ligeramente flexionados, sube hasta la altura del hombro.', 'Side_Lateral_Raise'],
  ['Curl de bíceps con mochila', 'biceps', 'c', 'iso', [], 'Codos pegados al cuerpo, sin balancear.', 'Dumbbell_Bicep_Curl'],
  ['Plancha', 'core', 'c', 'iso', [], 'Cuerpo recto, abdomen y glúteos apretados. Mantén el tiempo indicado.', 'Plank'],
  ['Plancha lateral', 'core', 'c', 'iso', [], 'Cadera alta, cuerpo en línea. Cambia de lado.', 'Side_Bridge'],
  ['Dead bug', 'core', 'c', 'iso', [], 'Lumbar pegada al suelo mientras alternas brazo y pierna.', 'Dead_Bug'],
  ['Mountain climbers', 'core', 'c', 'iso', ['mun'], 'Ritmo constante, caderas bajas.', 'Mountain_Climbers'],
  ['Crunch abdominal', 'core', 'c', 'iso', [], 'Sube con control, sin tirar del cuello.', 'Crunches'],
  // ----- GIMNASIO -----
  ['Press de banca con barra', 'pecho', 'g', 'comp', ['hom'], 'Escápulas juntas, barra al pecho medio, empuja en vertical.', 'Barbell_Bench_Press_-_Medium_Grip'],
  ['Press inclinado con mancuernas', 'pecho', 'g', 'comp', ['hom'], 'Banco a 30°, baja hasta sentir estiramiento en el pecho.', 'Incline_Dumbbell_Press'],
  ['Aperturas en polea', 'pecho', 'g', 'iso', [], 'Codos ligeramente flexionados, junta las manos al frente.', 'Cable_Crossover'],
  ['Jalón al pecho', 'espalda', 'g', 'comp', [], 'Tira hacia la clavícula llevando los codos abajo.', 'Wide-Grip_Lat_Pulldown'],
  ['Remo con barra', 'espalda', 'g', 'comp', ['esp'], 'Torso a 45°, espalda recta, tira hacia el ombligo.', 'Bent_Over_Barbell_Row'],
  ['Remo en polea baja', 'espalda', 'g', 'comp', [], 'Pecho alto, junta escápulas al final.', 'Seated_Cable_Rows'],
  ['Remo con mancuerna a una mano', 'espalda', 'g', 'comp', [], 'Apoya una mano en el banco y tira con el codo hacia la cadera.', 'One-Arm_Dumbbell_Row'],
  ['Sentadilla con barra', 'pierna', 'g', 'comp', ['rod', 'esp'], 'Barra estable en trapecios, baja hasta paralelo o más.', 'Barbell_Squat'],
  ['Prensa de piernas', 'pierna', 'g', 'comp', ['rod'], 'Pies a la anchura de caderas, no bloquees las rodillas.', 'Leg_Press'],
  ['Extensión de cuádriceps', 'pierna', 'g', 'iso', ['rod'], 'Controla la bajada, pausa arriba.', 'Leg_Extensions'],
  ['Curl femoral tumbado', 'gluteo', 'g', 'iso', [], 'Cadera pegada al banco, baja lento.', 'Lying_Leg_Curls'],
  ['Peso muerto rumano con barra', 'gluteo', 'g', 'comp', ['esp'], 'Cadera atrás, barra pegada a las piernas, espalda neutra.', 'Romanian_Deadlift'],
  ['Hip thrust con barra', 'gluteo', 'g', 'comp', [], 'Empuja con talones, aprieta glúteos arriba.', 'Barbell_Hip_Thrust'],
  ['Zancadas con mancuernas', 'pierna', 'g', 'comp', ['rod'], 'Pasos largos y controlados.', 'Dumbbell_Lunges'],
  ['Elevación de gemelos de pie', 'pierna', 'g', 'iso', [], 'Recorrido completo, pausa arriba.', 'Standing_Calf_Raises'],
  ['Press militar con mancuernas', 'hombro', 'g', 'comp', ['hom'], 'Core firme, empuja sin arquear la espalda.', 'Dumbbell_Shoulder_Press'],
  ['Elevaciones laterales con mancuernas', 'hombro', 'g', 'iso', [], 'Sube hasta la altura del hombro, baja lento.', 'Side_Lateral_Raise'],
  ['Face pull en polea', 'hombro', 'g', 'iso', [], 'Tira hacia la cara abriendo los codos.', 'Face_Pull'],
  ['Curl de bíceps con mancuernas', 'biceps', 'g', 'iso', [], 'Sin balanceo, supina la muñeca al subir.', 'Dumbbell_Bicep_Curl'],
  ['Curl martillo', 'biceps', 'g', 'iso', [], 'Agarre neutro, codos fijos.', 'Hammer_Curls'],
  ['Extensión de tríceps en polea', 'triceps', 'g', 'iso', [], 'Codos pegados, extiende por completo.', 'Triceps_Pushdown'],
  ['Press francés con mancuerna', 'triceps', 'g', 'iso', ['hom'], 'Baja detrás de la cabeza con control.', 'Standing_Dumbbell_Triceps_Extension'],
  ['Fondos en paralelas', 'triceps', 'g', 'comp', ['hom'], 'Torso algo inclinado, baja hasta 90° en los codos.', 'Dips_-_Triceps_Version'],
  ['Crunch en polea', 'core', 'g', 'iso', [], 'Redondea el torso llevando los codos a las rodillas.', 'Cable_Crunch'],
  ['Plancha con peso', 'core', 'g', 'iso', [], 'Anillo o disco sobre la espalda, cuerpo recto.', 'Plank'],
  ['Elevación de piernas colgado', 'core', 'g', 'iso', ['esp'], 'Sin balanceo, sube las rodillas al pecho.', 'Hanging_Leg_Raise']
];
const EXERCISES = EX_ROWS.map((r, i) => ({ id: 'e' + i, n: r[0], g: r[1], place: r[2], kind: r[3], risk: r[4], tip: r[5], img: r[6] || null }));
const EX_PLACE = { c: 'Casa', g: 'Gimnasio' };
